#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SUDOERS_FILE="/etc/sudoers.d/uftc-build-nopasswd"
D2VM_WRAPPER="$SCRIPT_DIR/d2vm"
BUILD_AB_DISK_SCRIPT="$SCRIPT_DIR/build-ab-disk.sh"
TARGET_USER="${SUDO_USER:-${USER:-}}"
ACTION="install"

collect_docker_bins() {
  local bins=()
  local path

  # Include all currently resolvable docker commands in PATH.
  if command -v docker >/dev/null 2>&1; then
    while IFS= read -r path; do
      [[ -n "$path" ]] && bins+=("$path")
    done < <(type -ap docker 2>/dev/null || true)
  fi

  # Include common Docker locations so rules still work after install changes.
  for path in /usr/bin/docker /usr/local/bin/docker /snap/bin/docker; do
    bins+=("$path")
  done

  printf '%s\n' "${bins[@]}" | awk 'NF && !seen[$0]++'
}

usage() {
  cat <<'EOF'
Usage: ./setup-build-sudoers.sh [options]

Installs or removes static passwordless sudo rules for the UFTC build pipeline.
Dependencies are managed separately via setup-build-deps.sh.

Options:
  --user NAME     Linux username for sudoers rule (default: current user)
  --remove        Remove the static build sudoers rule file
  -h, --help      Show this help message
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --user)
      if [[ $# -lt 2 ]]; then
        echo "Missing value for $1" >&2
        exit 1
      fi
      TARGET_USER="$2"
      shift 2
      ;;
    --remove)
      ACTION="remove"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "$TARGET_USER" ]]; then
  echo "Could not determine target user. Use --user NAME." >&2
  exit 1
fi

if [[ "$ACTION" == "remove" ]]; then
  sudo rm -f "$SUDOERS_FILE"
  echo "Removed static build sudoers rule: $SUDOERS_FILE"
  exit 0
fi

if [[ ! -f "$D2VM_WRAPPER" ]]; then
  echo "d2vm wrapper not found: $D2VM_WRAPPER" >&2
  exit 1
fi

if [[ ! -f "$BUILD_AB_DISK_SCRIPT" ]]; then
  echo "build-ab-disk script not found: $BUILD_AB_DISK_SCRIPT" >&2
  exit 1
fi

tmp_file="$(mktemp)"
trap 'rm -f "$tmp_file"' EXIT

cat >"$tmp_file" <<EOF
# Static passwordless sudo rules for UFTC build pipeline
# Generated by setup-build-sudoers.sh
# Remove with: ./setup-build-sudoers.sh --remove

# d2vm conversion used by build.sh
$TARGET_USER ALL=(root) NOPASSWD: $D2VM_WRAPPER
$TARGET_USER ALL=(root) NOPASSWD: $D2VM_WRAPPER convert *
$TARGET_USER ALL=(root) NOPASSWD: $D2VM_WRAPPER *

# A/B disk assembly used by build.sh --ab
$TARGET_USER ALL=(root) NOPASSWD: $BUILD_AB_DISK_SCRIPT
$TARGET_USER ALL=(root) NOPASSWD: $BUILD_AB_DISK_SCRIPT --prod-vhd * --recovery-vhd * --output *
$TARGET_USER ALL=(root) NOPASSWD: $BUILD_AB_DISK_SCRIPT --prod-vhd * --recovery-vhd * --output * --skip-efi
EOF

{
  echo ""
  echo "# Docker build commands used by build.sh"
  while IFS= read -r docker_bin; do
    echo "$TARGET_USER ALL=(root) NOPASSWD: $docker_bin build *"
  done < <(collect_docker_bins)
} >>"$tmp_file"

sudo visudo -cf "$tmp_file" >/dev/null
sudo install -m 0440 "$tmp_file" "$SUDOERS_FILE"

echo "Static build sudoers rule installed: $SUDOERS_FILE"
echo ""
echo "Runner/dev setup:"
echo "  1) bash ./setup-build-deps.sh"
echo "  2) ./setup-build-sudoers.sh"
echo ""

