#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SUDOERS_FILE="/etc/sudoers.d/uftc-build-nopasswd"
BUILD_SCRIPT="$SCRIPT_DIR/build.sh"
BUILD_AB_DISK_SCRIPT="$SCRIPT_DIR/build-ab-disk.sh"
BUILD_ISO_SCRIPT="$SCRIPT_DIR/build-installer-iso.sh"
TARGET_USER="${SUDO_USER:-${USER:-}}"
ACTION="install"

usage() {
  cat <<'EOF'
Usage: ./setup-build-sudoers.sh [options]

Installs or removes static passwordless sudo rules for the UFTC build pipeline.
Dependencies are managed separately via setup-build-deps.sh.

Options:
  --user NAME     Linux username for sudoers rule (default: current user)
  --remove        Remove the static build sudoers rule file
  -h, --help      Show this help message
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --user)
      if [[ $# -lt 2 ]]; then
        echo "Missing value for $1" >&2
        exit 1
      fi
      TARGET_USER="$2"
      shift 2
      ;;
    --remove)
      ACTION="remove"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "$TARGET_USER" ]]; then
  echo "Could not determine target user. Use --user NAME." >&2
  exit 1
fi

if [[ "$ACTION" == "remove" ]]; then
  sudo rm -f "$SUDOERS_FILE"
  echo "Removed static build sudoers rule: $SUDOERS_FILE"
  exit 0
fi

if [[ ! -f "$BUILD_SCRIPT" ]]; then
  echo "build script not found: $BUILD_SCRIPT" >&2
  exit 1
fi

if [[ ! -f "$BUILD_AB_DISK_SCRIPT" ]]; then
  echo "build-ab-disk script not found: $BUILD_AB_DISK_SCRIPT" >&2
  exit 1
fi

if [[ ! -f "$BUILD_ISO_SCRIPT" ]]; then
  echo "build-installer-iso script not found: $BUILD_ISO_SCRIPT" >&2
  exit 1
fi

tmp_file="$(mktemp)"
trap 'rm -f "$tmp_file"' EXIT

cat >"$tmp_file" <<EOF
# Static passwordless sudo rules for UFTC build pipeline
# Generated by setup-build-sudoers.sh
# Remove with: ./setup-build-sudoers.sh --remove

# Top-level build entrypoints
$TARGET_USER ALL=(root) NOPASSWD: $BUILD_SCRIPT
$TARGET_USER ALL=(root) NOPASSWD: $BUILD_ISO_SCRIPT

# A/B disk assembly helper used by build.sh --ab
$TARGET_USER ALL=(root) NOPASSWD: $BUILD_AB_DISK_SCRIPT
EOF

sudo visudo -cf "$tmp_file" >/dev/null
sudo install -m 0440 "$tmp_file" "$SUDOERS_FILE"

echo "Static build sudoers rule installed: $SUDOERS_FILE"
echo ""
echo "Runner/dev setup:"
echo "  1) bash ./setup-build-deps.sh"
echo "  2) ./setup-build-sudoers.sh"
echo ""

