# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

TTY="$(/usr/bin/tty 2>/dev/null | sed 's:.*/::')"

# Only auto-launch X on the local interactive console.
# Keep serial sessions text-only for troubleshooting.
if [[ -z ${DISPLAY} && ( ${TTY} == 'tty1' || ${TTY} == 'console' || ${TTY} == 'hvc0' ) ]]; then
    mode="legacy"
    fail_count=0
    if [ -r /proc/cmdline ]; then
        for token in $(cat /proc/cmdline); do
            case "$token" in
                rdos.ui=web)
                    mode="web"
                    break
                    ;;
                rdos.ui=legacy)
                    mode="legacy"
                    break
                    ;;
            esac
        done
    fi

    udiskie &

    # Keep retrying X startup so transient failures do not leave the user at a shell.
    while true; do
        if [ "$mode" = "web" ]; then
            startx /usr/bin/tc-ui-launch >>"$HOME/.startx.log" 2>&1
        else
            startx >>"$HOME/.startx.log" 2>&1
        fi
        startx_rc=$?

        if [ "$startx_rc" -eq 0 ]; then
            sleep 1
            continue
        fi

        fail_count=$((fail_count + 1))
        warning_msg="startx failed in ${mode} mode (exit ${startx_rc}); retrying."
        printf 'WARNING: %s\n' "$warning_msg" >&2
        if command -v logger >/dev/null 2>&1; then
            logger -t thinclient-bashrc "$warning_msg"
        fi

        if [ -s "$HOME/.startx.log" ]; then
            if grep -q 'Only console users are allowed to run the X server' "$HOME/.startx.log"; then
                printf '%s\n' 'ERROR: Xorg wrapper denied this login session. Check /etc/X11/Xwrapper.config (allowed_users=anybody).' >&2
            fi

            # Print recent logs on first failure and then every fifth retry to reduce console spam.
            if [ "$fail_count" -eq 1 ] || [ $((fail_count % 5)) -eq 0 ]; then
                printf '%s\n' '--- recent ~/.startx.log ---' >&2
                tail -n 40 "$HOME/.startx.log" >&2
                printf '%s\n' '--- end ~/.startx.log ---' >&2
            fi
        fi

        sleep 2
    done

    unset TTY mode fail_count
fi