#!/bin/sh
# Start overlay daemon
if command -v /usr/bin/tc-overlay-daemon >/dev/null 2>&1; then
    /usr/bin/tc-overlay-daemon -tcconfig="${HOME}/tcconfig" -log="${HOME}/.tc-overlay.log" >/dev/null 2>&1 &
fi

exec fvwm