#!/bin/sh

mode="legacy"
if [ -r /proc/cmdline ]; then
	for token in $(cat /proc/cmdline); do
		case "$token" in
			rdos.ui=web)
				mode="web"
				break
				;;
			rdos.ui=legacy)
				mode="legacy"
				break
				;;
		esac
	done
fi

if [ "$mode" = "web" ]; then
	exec /usr/bin/tc-ui-launch
fi

exec fvwm